### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by AquaRelliux** [Herlix/homebridge-plejd#11]
I would love for this one to work on docker or at least a guide to get it working :)

**Comment by Herlix** [comment]
Hey! 

This should work now :) 

I'm rocking this docker compose setup: 
```  
homebridge:
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /home/pi/.homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
```
